frontend:
  build: ./frontend/
  dockerfile: Dockerfile
  links:
      - backend
  ports:
      - "8080:2015"
  volumes:
      - ./frontend:/site/

backend:
  build: ./backend/
  dockerfile: Dockerfile
  links:
      - db
  volumes:
      - ./backend:/go/src/github.com/guilhermebr/backenderia/backend

db:
  image: mongo
  volumes:
       - ./db:/var/lib/mongodb
  restart: always
